for repo in "group-b" "group-c" "group-f" "group-g" "group-i" "group-m"
do sqlite3 -csv ../data/databases/${repo}.db "select cl.issueID, (cl.time - op.time) as timeOpen from event cl, (select issueID, min(time) as time from event group by issueID) op where cl.action == 'closed' AND cl.issueID == op.issueID;" > ../data/csv/open_close/${repo}.csv
sqlite3 -csv ../data/databases/${repo}.db "select ev.issueID, ev.time-milestone.due_at as secondsAfter from (select issueID, time, milestone from event ev1 where action = 'closed' and milestone not null and time >= (select max(time) from event where issueID = ev1.issueID and action = 'closed')) ev, milestone where milestone.id = ev.milestone;" > ../data/csv/milestone_delay/${repo}.csv
sqlite3 -csv ../data/databases/${repo}.db "select e1.issueID, (e1.time - (mileDur.due_at - mileDur.duration)) as timeAfterStart, mileDur.duration as duration from event e1, (select m2.id, m2.due_at, (m2.due_at - m1.due_at) as duration from milestone m1, milestone m2 where m2.id = m1.id+1) mileDur where e1.milestone = mileDur.id and e1.action = 'closed' and e1.time >= (select max(time) from event where event.action = 'closed' and issueID = e1.issueID);" > ../data/csv/preshooting/${repo}.csv
sqlite3 -csv ../data/databases/${repo}.db "select label, count(*) from (select issueID, label from event e1 where action = 'assigned' and time >= (select max(time) from event where e1.issueID = issueID and action = 'assigned')) group by label;" > ../data/csv/assignments/${repo}.csv
sqlite3 -csv ../data/databases/${repo}.db "select issueID, count(distinct user) from comment group by issueID;" > ../data/csv/issue_comment/${repo}.csv
sqlite3 -csv ../data/databases/${repo}.db "select user, count(*) from event e1 where time <= (select min(time) from event where issueID = e1.issueID) group by user;" > ../data/csv/issue_create/${repo}.csv
sqlite3 -csv ../data/databases/${repo}.db "select issueID, count(*) from comment group by issueID;" > ../data/csv/issue_numcomments/${repo}.csv
sqlite3 -csv ../data/databases/${repo}.db "select bugs, count(distinct issueID) as issues, (bugs+0.0)/count(distinct issueID) as ratio from (select count(*) as bugs from event where lower(label) like '%bug%' and action == 'labeled'), event;" > ../data/csv/bugratio/${repo}.csv
sqlite3 -csv ../data/databases/${repo}.db "select user, sum(additions) from commits group by user;" > ../data/csv/additions/${repo}.csv
sqlite3 -csv ../data/databases/${repo}.db "select user, sum(deletions) from commits group by user;" > ../data/csv/deletions/${repo}.csv
sqlite3 -csv ../data/databases/${repo}.db "select user, sum(additions) - sum(deletions) from commits group by user;" > ../data/csv/changes_made/${repo}.csv
sqlite3 -csv ../data/databases/${repo}.db "select user, count(*) as comments from comment group by user;" > ../data/csv/comments_user/${repo}.csv
sqlite3 -csv ../data/databases/${repo}.db "select numShort, numTotal, (numShort+0.0)/numTotal from (select count(*) as numShort from event cl, (select issueID, min(time) as time from event group by issueID) op where cl.action == 'closed' AND cl.issueID == op.issueID and (cl.time - op.time) < 3600), (select count(distinct issueID) as numTotal from event);" > ../data/csv/short_open/${repo}.csv
sqlite3 -csv ../data/databases/${repo}.db "select user, sum(additions) - sum(deletions) from commits;" > ../data/csv/changes_per_commit/${repo}.csv
done
find ../data/csv/ -size  0 -exec rm '{}' \;